# Generated by Django 3.2 on 2022-07-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
